spring:
  datasource:
    url: jdbc:h2:file:./demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

flyway:
  enabled: true
  locations: db/migration/common,db/migration/h2,db/migration/demo

development:
  dataInitializer:
    enabled: false
  securityContext:
    enabled: true
  user:
    email: demo@codeball.com
    firstName: Demo
    lastName: User
    pictureUrl: https://rawgit.com/codeball-team/codeball/master/src/frontend/src/images/user-missing-picture.png
    role: ROLE_ADMIN


